# Generated by Django 4.2.5 on 2023-10-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_kino_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='posterstatic',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Постер в статик'),
        ),
    ]
