# Generated by Django 4.2.5 on 2023-10-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_kino_posterlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kino',
            old_name='posterlink',
            new_name='poster',
        ),
    ]
