# Generated by Django 4.2.5 on 2023-10-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_rename_posterlink_kino_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='summary',
            field=models.TextField(max_length=5000, verbose_name='Краткое описание'),
        ),
    ]
