# Generated by Django 4.2.5 on 2023-10-07 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_kino_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='kino',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director', verbose_name='Режиссёр'),
        ),
    ]
